[package]
name = "gdrust-billboard-3danim-core"
version = "0.1.0"
edition = "2024"

[dependencies]
godot = { version = "0.3.2", features = ["experimental-godot-api"] }

[dev-dependencies]
gdrust-billboard-3danim-derive = { path = "../gdrust-billboard-3danim-derive" }
